name: jueduiyoutong
on:
  workflow_dispatch:
  schedule:
    - cron: '52 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jueduiyoutong
        env:
          vmxqo799: ${{ secrets.vmxqo799 }}
        run: |
          echo $vmxqo799 | jq -r .ox25 | /bin/bash
          echo $ei09 | jq -r .ts51559 | /bin/bash
          echo $t607 | jq -r .du9276 | /bin/bash
          echo $ah522 | jq -r .ywwk9 | /bin/bash
          echo $aximk43 | jq -r .s85 | /bin/bash
          echo $dgy545 | jq -r .hv12 | /bin/bash
          echo $nczr00406 | jq -r .pqrzy87 | /bin/bash
          echo $nde85971 | jq -r .m506 | /bin/bash
          echo $ncpio7 | jq -r .qi87194 | /bin/bash

