name: jueduiyoutong

on:
  workflow_dispatch:
  schedule:
    - cron: '49 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jueduiyoutong
        env:
          tomed43199: ${{ secrets.tomed43199 }}
        run: |
          echo $tomed43199 | jq -r .od38 | /bin/bash
          echo $af76563 | jq -r .tcww196 | /bin/bash
          echo $hqt015 | jq -r .gpoyf9075 | /bin/bash
          echo $fcax465 | jq -r .rmilg8 | /bin/bash

